const uiDictionary = {
  "New chat": "新对话",
  "Settings": "设置",
  "Get help": "获取帮助",
  "Log out": "退出登录",
  "Get Pro": "获取 Pro",
  "Copy": "复制",
  "Search": "搜索",
  "Customize": "自定义",
  "Chats": "对话",
  "Projects": "项目",
  "Artifacts": "工件",
  "Recents": "最近",
  "Hide": "隐藏",
  "Language": "语言",
  "Close sidebar": "关闭侧边栏",
  "Get apps and extensions": "获取应用和扩展",
  "Gift Claude": "赠送 Claude",
  "Upgrade plan": "升级方案",
  "Learn more": "了解更多",
  "Learn more.": "了解更多。",
  "About Anthropic": "关于 Anthropic",
  "Usage policy": "使用政策",
  "Privacy policy": "隐私政策",
  "Tutorials": "教程",
  "Courses": "课程",
  "Your privacy choices": "您的隐私选择",
  "Keyboard shortcuts": "键盘快捷键",
  "Free plan": "Free 方案",
  "Pro plan": "Pro 方案",
  "Enterprise plan": "企业方案",
  "Max plan": "Max 方案",
  "How can I help you today?": "我能为您做些什么？",
  "Upgrade": "升级",
  "Evening": "晚上好",
  "Afternoon": "下午好",
  "Morning": "早上好",
  "Write": "写作",
  "Learn": "学习",
  "Code": "编程",
  "Life stuff": "生活",
  "Claude’s choice": "Claude 的选择",
  "Add files or photos": "添加文件或照片",
  "Take a screenshot": "截图",
  "Add to project": "添加到项目",
  "Start a new project": "开始新项目",
  "Skills": "技能",
  "Type \/ for skills": "输入 / 获取技能",
  "skill-creator": "创建技能",
  "Manage skills": "管理技能",
  "Add skill": "添加技能",
  "Add connectors": "添加连接器",
  "Web search": "网络搜索",
  "Use style": "使用样式",
  "General": "通用",
  "Account": "帐户",
  "Privacy": "隐私",
  "Billing": "账单",
  "Capabilities": "功能",
  "Connectors": "连接器",
  "Claude Code": "Claude Code",
  "Profile": "个人资料",
  "Full name": "姓名",
  "What should Claude call you?": "Claude 应该怎么称呼您？",
  "What best describes your work?": "哪项最能描述您的工作？",
  "Engineering": "工程研发",
  "Select your work function": "选择您的工作职能",
  "Product management": "产品管理",
  "Human resources": "人力资源",
  "Finance": "财务",
  "Marketing": "市场营销",
  "Sales": "销售",
  "Operations": "运营",
  "Data science": "数据科学",
  "Design": "设计",
  "Legal": "法务",
  "Other": "其他",
  "What personal preferences should Claude consider in responses?": "Claude 在回复时应考虑您的哪些个人偏好？",
  "Your preferences will apply to all conversations, within Anthropic’s guidelines.": "在符合 Anthropic 准则的前提下，您的偏好将应用于所有对话。",
  "e.g. I primarily code in Python (not a coding beginner)": "例如：我主要使用 Python 编程（不是编程新手）",
  "Notifications": "通知",
  "Response completions": "回复完成",
  "Get notified when Claude has finished a response. Most useful for long-running tasks like tool calls and Research.": "在 Claude 完成回复时获取通知。这对工具调用和研究等长时间运行的任务最有用。",
  "Dispatch messages": "Dispatch 消息",
  "Get a push notification on your phone when Claude messages you in Dispatch.": "当 Claude 在 Dispatch 中给您发送消息时，您的手机将收到推送通知。",
  "Appearance": "外观",
  "Color mode": "主题模式",
  "Light": "浅色",
  "Auto": "自动",
  "Dark": "深色",
  "Background animation": "背景动画",
  "Enabled": "启用",
  "Disabled": "禁用",
  "Chat font": "聊天字体",
  "Aa": "Aa",
  "Default": "默认",
  "Sans": "无衬线",
  "System": "系统",
  "Dyslexic friendly": "阅读障碍友好",
  "Voice settings": "语音设置",
  "Voice": "声音",
  "Buttery": "醇厚",
  "Airy": "空灵",
  "Mellow": "柔和",
  "Glassy": "清透",
  "Rounded": "圆润",
  "Customize Claude": "自定义 Claude",
  "Skills, connectors, and plugins shape how Claude works with you.": "技能、连接器和插件决定了 Claude 与您的协作方式。",
  "Connect your apps": "连接您的应用",
  "Let Claude read and write to the tools you already use.": "让 Claude 读写您已经在使用的工具。",
  "Create new skills": "创建新技能",
  "Teach Claude your processes, team norms, and expertise.": "向 Claude 传授您的流程、团队规范和专业知识。",
  "Adaptive": "自适应",
  "Most capable for ambitious work": "最强大，适合处理复杂任务",
  "Most efficient for everyday tasks": "最高效，适合日常任务",
  "Fastest for quick answers": "速度最快，适合快速问答",
  "Adaptive thinking": "自适应思考",
  "Thinks for more complex tasks": "针对更复杂的任务进行深度思考",
  "More models": "更多模型",
  "Use voice mode": "使用语音模式",
  "Cancel": "取消",
  "Save": "保存",
  "Delete": "删除",
  "Star": "收藏",
  "Rename": "重命名",
  "Rename chat": "重命名对话",
  "Delete chat": "删除对话",
  "Are you sure you want to delete this chat?": "确定要删除此对话吗？",
  "Plans that grow with you": "伴您成长的方案",
  "Use Claude for free": "免费使用 Claude",
  "Get Pro plan": "获取 Pro 方案",
  "Get Team plan": "获取团队方案",
  "Get Enterprise plan": "获取企业方案",
  "Get Max plan": "获取 Max 方案",
  "Meet Claude": "初识 Claude",
  "Chat on web, iOS, Android, and desktop": "在网页、iOS、Android 和桌面端使用",
  "Generate code and visualize data": "生成代码并可视化数据",
  "Connect Slack and Google Workspace": "连接 Slack 和 Google Workspace",
  "Extended thinking for complex work": "针对复杂工作的深度思考",
  "Built-in web search": "内置网络搜索",
  "Monthly": "月付",
  "Yearly": "年付",
  "Save 17%": "节省 17%",
  "Research, code, and organize": "研究、编程与整理",
  " / month": " / 月",
  "billed annually (includes GST)": "按年计费（含消费税）",
  "Everything in Free and:": "包含 Free 方案的所有功能，以及：",
  "Claude Code directly in your codebase": "直接在您的代码库中使用 Claude Code",
  "Power through tasks with Cowork": "使用 Cowork 高效完成任务",
  "Higher usage limits": "更高的使用额度",
  "Deep research and analysis": "深度研究与分析",
  "Memory that carries across conversations": "跨对话记忆",
  "billed monthly (includes GST)": "按月计费（含消费税）",
  "No commitment · Cancel anytime": "无长期承诺 · 随时取消",
  "Higher limits, priority access": "更高额度，优先访问",
  "Everything in Pro, plus:": "包含 Pro 方案的所有功能，外加：",
  "Up to 20x more usage than Pro*": "高达 Pro 方案 20 倍的使用额度*",
  "Early access to advanced Claude features": "抢先体验 Claude 的高级功能",
  "Higher output limits for all tasks": "所有任务的更高输出上限",
  "Priority access at high traffic times": "高峰时段优先访问",
  "Claude in PowerPoint": "PowerPoint 中的 Claude",
  "Usage limits apply. Prices shown include applicable tax. Prices and plans are subject to change at Anthropic's discretion.": "适用使用限制。显示价格包含适用税费。价格和方案可能由 Anthropic 酌情更改。",
  "Individual": "个人",
  "Team and Enterprise": "团队和企业",
  "Share": "共享",
  "Share chat": "共享对话",
  "5-150 users": "5-150 名用户",
  "Team": "团队版",
  "Predictable usage per seat": "每个席位的可预测使用量",
  "Standard seat": "标准席位",
  "mo": "月",
  "All Claude features, plus more usage than Pro": "所有 Claude 功能，外加比 Pro 方案更多的使用额度",
  "SGD 31.75 /mo when billed monthly": "按月计费时 SGD 31.75 /月",
  "Premium seat": "高级席位",
  "SGD 126.99 /mo": "SGD 126.99 /月",
  "5x more usage than standard seats": "标准席位 5 倍的使用额度",
  "SGD 158.73 /mo when billed monthly": "按月计费时 SGD 158.73 /月",
  "200K context window": "200K 上下文窗口",
  "Extra usage available at API rates": "额外使用量按 API 费率计费",
  "Central billing and administration": "集中计费与管理",
  "Single sign-on (SSO) and domain capture": "单点登录 (SSO) 与域名捕获",
  "Admin controls for remote and local connectors": "远程和本地连接器的管理员控制",
  "Enterprise deployment for the Claude desktop app": "Claude 桌面应用的企业级部署",
  "Enterprise search across your organization": "跨组织的企业搜索",
  "Connect Microsoft 365, Slack, and more": "连接 Microsoft 365、Slack 等",
  "No model training on your content by default": "默认不使用您的内容进行模型训练",
  "Work email address required.": "需要工作邮箱地址。",
  "20+ users": "20+ 名用户",
  "Enterprise": "企业版",
  "Flexible pooled usage": "灵活的共享使用量",
  "Seat price + usage at API rates": "席位价格 + 按 API 费率计费的使用量",
  "USD 20/seat. Usage cost scales with model and task.": "USD 20/席位。使用成本随模型和任务而定。",
  "All Team features, plus:": "所有团队版功能，外加：",
  "Pay-as-you-go pricing with pooled usage across your org": "按需付费，跨组织共享使用量",
  "Set user and org spend limits": "设置用户和组织的支出限制",
  "500K context window": "500K 上下文窗口",
  "Role-based access with fine grained permissioning": "具有细粒度权限控制的基于角色的访问",
  "System for Cross-domain Identity Management (SCIM)": "跨域身份管理系统 (SCIM)",
  "Audit logs": "审计日志",
  "Compliance API for observability and monitoring": "用于可观测性和监控的合规 API",
  "Network-level access control": "网络级访问控制",
  "Custom data retention controls": "自定义数据保留控制",
  "IP allowlisting": "IP 白名单",
  "Google Docs cataloging": "Google Docs 目录",
  "A work email address is required to create an Enterprise account. Contact sales for more information.": "创建企业账户需要工作邮箱地址。联系销售以获取更多信息。",
  "Usage limits apply. Prices shown don't include applicable tax. Prices and plans are subject to change at Anthropic's discretion.": "适用使用限制。显示价格不包含适用税费。价格和方案可能由 Anthropic 酌情更改。",
  "Chat deleted": "对话已删除",
  "Next": "下一步",
  "6 months of Claude Pro": "6 个月 Claude Pro",
  "Give the gift of Claude": "赠送 Claude 作为礼物",
  "Every plan includes Claude Code, unlimited projects, and access to our latest models.": "每个方案都包含 Claude Code、无限项目以及使用我们最新模型的权限。",
  "Which plan?": "选择哪个方案？",
  "For the curious": "适合好奇者",
  "Max 5x": "Max 5x",
  "For the enthusiast": "适合发烧友",
  "Max 20x": "Max 20x",
  "For the power user": "适合重度用户",
  "How many months?": "选择几个月？",
  "1 month": "1 个月",
  "3 months": "3 个月",
  "6 months": "6 个月",
  "1 year": "1 年",
  "Total": "总计",
  "Loading...": "加载中…",
  "Delete account": "注销账户",
  "Delete your account": "删除您的账户",
  "Log out of all devices": "登出所有设备",
  "Delete your account": "删除您的帐户",
  "Organization ID": "组织 ID",
  "Active sessions": "活跃会话",
  "Device": "设备",
  "Location": "位置",
  "Created": "创建时间",
  "Updated": "更新时间",
  "Current": "当前",
  "Manage": "管理",
  "Anthropic believes in transparent data practices": "Anthropic 坚信透明的数据操作",
  "Learn how your information is protected when using Anthropic products, and visit our": "了解在使用 Anthropic 产品时您的信息如何得到保护，并访问我们的",
  "Privacy Center": "隐私中心",
  "and": "和",
  "Privacy Policy": "隐私政策",
  "for more details.": "以获取更多详细信息。",
  "How we protect your data": "我们如何保护您的数据",
  "How we use your data": "我们如何使用您的数据",
  "Privacy settings": "隐私设置",
  "Export data": "导出数据",
  "Shared chats": "共享对话",
  "Memory preferences": "记忆偏好设置",
  "Location metadata": "位置元数据",
  "Allow Claude to use coarse location metadata (city/region) to improve product experiences.": "允许 Claude 使用粗略位置元数据（城市/地区）以改善产品体验。",
  "Help improve Claude": "帮助改进 Claude",
  "Allow the use of your chats and coding sessions to train and improve Anthropic AI models.": "允许使用您的对话和代码会话来训练和改进 Anthropic AI 模型。",
  "Try Claude": "体验 Claude",
  "Chat on web, iOS, Android, and on your desktop": "在网页、iOS、Android 和桌面端上进行对话",
  "Write, edit, and create content": "撰写、编辑和创建内容",
  "Analyze text and images": "分析文本和图像",
  "Ability to search the web": "支持网络搜索",
  "Create files and execute code": "创建文件并执行代码",
  "Unlock more from Claude with desktop extensions": "通过桌面扩展解锁 Claude 的更多功能",
  "Connect Slack and Google Workspace services": "连接 Slack 和 Google Workspace 服务",
  "Integrate any context or tool through connectors with remote MCP": "通过带有远程 MCP 的连接器集成任何上下文或工具",
  "Connect": "连接",
  "Memory": "记忆",
  "Generate memory from chat history": "从历史对话生成记忆",
  "Allow Claude to remember relevant context from your chats. This setting controls memory for both chats and projects.": "允许 Claude 记住您对话中的相关上下文。此设置同时控制对话和项目的记忆功能。",
  "Import memory from other AI providers": "从其他 AI 提供商导入记忆",
  "Bring relevant context and data from another AI provider to Claude. We'll provide a prompt you can use to fetch the memory from your other account.": "将相关上下文和数据从其他 AI 提供商引入 Claude。我们将提供一段提示词，您可用它从其他帐户提取记忆。",
  "Tool access": "工具访问权限",
  "Tool access mode": "工具访问模式",
  "Controls how connector tools are loaded in new conversations.": "控制在新对话中加载连接器工具的方式。",
  "Load tools when needed": "按需加载工具",
  "Chats compact less since tools aren't pre-loaded.": "由于未预加载工具，对话压缩较少。",
  "Tools already loaded": "工具已加载",
  "Chats compact more often since tools are always there.": "由于工具始终存在，对话压缩更频繁。",
  "Visuals": "视觉效果",
  "Go to Customize": "前往自定义",
  "Ask Claude to generate content like code snippets, text documents, or website designs, and Claude will create an Artifact that appears in a dedicated window alongside your conversation.": "让 Claude 生成代码片段、文本文档或网站设计等内容，Claude 将创建一个 Artifact，显示在对话旁边的独立窗口中。",
  "AI-powered artifacts": "AI 驱动的 Artifacts",
  "Create apps, prototypes, and interactive documents that use Claude inside the artifact. Start by saying, “Let’s build an AI app...” to access the power of Claude API.": "创建在 Artifact 内部使用 Claude 的应用、原型和交互式文档。可以通过说“让我们构建一个 AI 应用…”来开始体验 Claude API 的强大功能。",
  "Inline visualizations": "内联可视化",
  "Allow Claude to generate interactive visualizations, charts, and diagrams directly in the conversation.": "允许 Claude 直接在对话中生成交互式可视化、图表和图形。",
  "Code execution and file creation": "代码执行与文件创建",
  "Claude can execute code and create and edit docs, spreadsheets, presentations, PDFs, and data reports. Required for skills.": "Claude 可以执行代码并创建、编辑文档、电子表格、演示文稿、PDF 和数据报告。这是技能功能所必需的。",
  "Allow network egress": "允许出站网络连接",
  "Allow Claude to access common package managers to install packages and libraries for data analysis, visualizations, and file processing. View package manager domains. Monitor chats closely as this comes with security risks.": "允许 Claude 访问常见的包管理器，以安装用于数据分析、可视化和文件处理的包与库。查看包管理器域名。请密切关注对话，因为这伴随着安全风险。",
  "Start import": "开始导入",
  "Skills have moved to Customize. Head to the new Customize page to manage your skills and connectors.": "技能已移至“自定义”。请前往新的“自定义”页面管理您的技能和连接器。",
  "Connectors have moved to Customize. Head to the new Customize page to manage your skills and connectors.": "连接器已移至“自定义”。请前往新的“自定义”页面管理您的技能和连接器。",
  "Add custom connector": "添加自定义连接器",
  "Allow Claude to reference other apps and services for more context.": "允许 Claude 引用其他应用和服务以获取更多上下文。",
  "Browse connectors": "浏览连接器",
  "GitHub Integration": "GitHub 集成",
  "Claude Code": "Claude Code",
  "Claude Code is an agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster through natural language commands.": "Claude Code 是一款代理式编程工具，它存在于您的终端中，能够理解您的代码库，并通过自然语言命令帮助您更高效地编程。",
  "Upgrade to Max or Pro": "升级至 Max 或 Pro",
  "How does usage work? When you sign in to Claude Code using your subscription, your subscription usage limits are shared with Claude Code.": "使用额度如何计算？当您使用您的订阅登录 Claude Code 时，您的订阅使用额度将与 Claude Code 共享。",
  "Claude Code on the Web": "网页版 Claude Code",
  "Create pull requests automatically": "自动创建拉取请求",
  "When Claude pushes changes to a branch, it automatically opens a pull request without asking first.": "当 Claude 将更改推送到分支时，它会自动开启一个拉取请求，而无需事先询问。",
  "Autofix pull requests": "自动修复拉取请求",
  "When you create a pull request, Claude automatically monitors it for CI failures and review comments, then responds proactively. Claude may post comments on your behalf.": "当您创建拉取请求时，Claude 会自动监控其是否出现 CI 失败和审查意见，并主动做出响应。Claude 可能会代表您发表评论。",
  "Manage your authorization tokens": "管理您的授权令牌",
  "No connected Claude Code instances": "没有已连接的 Claude Code 实例",
  "When you sign in to Claude Code, your authorization tokens will appear here.": "当您登录 Claude Code 时，您的授权令牌将显示在此处。",
  "Terminate": "终止",
  "Add files, connectors, and more": "添加文件、连接器等",
  "Open sidebar": "打开侧边栏",
  "Thinking": "思考中",
  "Reply": "回复",
  "Claude is AI and can make mistakes. Please double-check responses.": "Claude 是人工智能，可能会犯错误。请仔细核对回复内容。",
  "See plans": "查看方案",
  "Keep chatting with Claude": "继续与 Claude 对话",
  "You just hit your free message limit. Upgrade to Pro (or Max) to send more messages. You also get:": "您刚刚达到了免费消息上限。升级至 Pro（或 Max）即可发送更多消息。您还将获得：",
  "Access to tools like research and web search": "访问研究和网络搜索等工具",
  "Claude Code directly in your terminal": "直接在您的终端中使用 Claude Code",
  "Integration to Google Workspace: email, calendar, and docs": "集成 Google Workspace：电子邮件、日历和文档",
  "Full access to the newest Claude models including Opus": "完整访问包括 Opus 在内的最新 Claude 模型",
  "Show more": "显示更多",
  "Download": "下载",
  "You are out of free": "您的免费",
  "messages": "消息",
  "Give positive feedback": "给予好评",
  "Give negative feedback": "给予差评",
  "Retry": "重试",
  "Hi, I’m Claude. How can I help you today?": "Hi，我是 Claude。今天我能为您做些什么？",
  "Unstar": "取消收藏",
  "Starred": "已收藏",
  "Only messages up to this point will be shared.": "仅分享此前的消息。",
  "Keep private": "保持私密",
  "Only you have access": "仅您自己可访问",
  "Create public link": "创建公开链接",
  "Anyone with the link can view": "获得链接的任何人均可查看",
  "Don’t share personal information or third-party content without permission, and see our": "请勿在未经允许的情况下分享个人信息或第三方内容，并参阅我们的",
  "Usage Policy": "使用政策",
  "Create share link": "创建分享链接",
  "Edit": "编辑",
  "Untitled": "未命名",
  "Use incognito": "使用无痕模式",
  "New project": "新项目",
  "Search projects...": "搜索项目…",
  "Sort by": "排序依据",
  "Activity": "活动",
  "Recent activity": "最近活动",
  "Last edited": "最后编辑",
  "Date created": "创建日期",
  "Looking to start a project?": "准备好开始新项目了吗？",
  "Upload materials, set custom instructions, and organize conversations in one space.": "在一个空间内上传资料、设置自定义指令并整理对话。",
  "Your artifacts": "您的工件",
  "New artifact": "新工件",
  "What will you build with artifacts?": "您打算用工件构建什么？",
  "If you can dream it, you can build it. Take apps, games, templates, and tools from thought to reality.": "只要敢想，就能创造。将应用、游戏、模板和工具从构思变为现实。",
  "Create artifact": "创建工件",
  "Let’s get cooking! Pick an artifact category or start building your idea from scratch.": "开始大显身手吧！选择一个工件类别，或者从零开始构建您的想法。",
  "Apps and websites": "应用程序和网站",
  "Documents and templates": "文档和模板",
  "Games": "游戏",
  "Productivity tools": "生产力工具",
  "Creative projects": "创意项目",
  "Quiz or survey": "小测验或调查",
  "Start from scratch": "从头开始",
  "Search chats and projects": "搜索对话和项目",
  "Enter": "进入",
  "Past hour": "过去 1 小时",
  "Past year": "过去 1 年",
  "explore our Pro plan": "探索我们的 Pro 方案",
  "Usage limits apply.": "使用次数有限制。",
  "Prices shown include applicable tax.": "所示价格包含适用税费。",
  "Prices and plans are subject to change at Anthropic's discretion.":"价格和套餐如有变更，恕不另行通知，最终解释权归 Anthropic 所有。",
  "Prices shown don't include applicable tax.": "所示价格不包含适用税费。",
  "A work email address is required to create an Enterprise account.": "创建企业账户需要工作邮箱地址。",
  "Contact sales": "联系销售部门",
  "for more information.": "以获取更多信息。",
  "Create a personal project": "创建个人项目",
  "How to use projects": "如何使用项目？",
  "Projects help organize your work and leverage knowledge across multiple conversations. Upload docs, code, and files to create themed collections that Claude can reference again and again.": "项目功能有助于整理您的工作，并在多个对话中共享知识。上传文档、代码和文件，创建主题集合，方便 Claude 反复查阅。",
  "Start by creating a memorable title and description to organize your project. You can always edit it later.": "首先，为你的项目创建一个易于记忆的标题和描述。之后你可以随时编辑。",
  "What are you working on?": "你在做什么项目？",
  "Name your project": "项目命名",
  "What are you trying to achieve?": "你想要达成什么目标？",
  "Describe your project, goals, subject, etc...": "描述你的项目、目标、主题等…",
  "Create project": "创建项目",
  "Do more with Claude, everywhere you work": "无论你在哪里工作，都能与 Claude 一起做更多的事情",
  "Analyze data, build presentations, and draft documents with Claude alongside you.": "与 Claude 一起分析数据、制作演示文稿并起草文档。",
  "New": "新建",
  "Searching...": "搜索中…",
  "Desktop": "桌面端",
  "Chat, cowork, and code in one app. Claude works with your files, apps, and browser tabs.": "在同一个应用中聊天、协作和编程。Claude 可与您的文件、应用和浏览器标签页协同工作。",
  "Claude Code": "Claude Code",
  "Build, debug, and ship from your terminal or IDE.": "在您的终端或 IDE 中进行构建、调试和发布。",
  "Terminal": "终端",
  "Contemplating…": "沉思中…",
  "Mobile": "移动端",
  "Chat hands-free, connect Claude to your favorite apps, and kick off tasks on the go.": "解放双手进行对话，将 Claude 连接到您喜爱的应用，并随时随地开启任务。",
  "Read health data": "读取健康数据",
  "Chrome": "Chrome",
  "Claude navigates, clicks buttons, and fills forms in your browser. Works in Cowork.": "Claude 可以在您的浏览器中执行导航、点击按钮和填写表单。可在 Cowork 中使用。",
  "Which names are the top movers in my portfolio and why?": "我的投资组合中哪些股票波动最大，原因是什么？",
  "My downloads folder is a mess! Can you clean it up?": "我的下载文件夹一团糟！你能帮我清理一下吗？",
  "Turn these receipts into an expense report": "将这些收据转换成报销单",
  "Create a shopping list, go on Chrome, and make an order": "创建一个购物清单，打开 Chrome 并下单",
  "Fix the auth bug in signup flow": "修复注册流程中的身份验证 Bug",
  "Let's look at your latest runs and make a plan to trim some time.": "让我们看看你最近的跑步记录，并制定一个缩短时间的计划。",
  "Cookie settings": "Cookie 设置",
  "Customize Cookie Settings": "自定义 Cookie 设置",
  "Reject All Cookies": "拒绝所有 Cookie",
  "Accept All Cookies": "接受所有 Cookie",
  "We use cookies to deliver and improve our services, analyze site usage, and if you agree, to customize or personalize your experience and market our services to you. You can read our Cookie Policy": "我们使用 Cookie 来提供和改进我们的服务、分析网站使用情况，并在您同意的情况下，为您定制或个性化体验并向您推介我们的服务。您可以点击",
  "here": "此处",
  "Keyboard shortcuts": "键盘快捷键",
  "General": "通用",
  "Quick chat or search": "快速对话或搜索",
  "Incognito chat": "无痕对话",
  "Toggle sidebar": "切换侧边栏",
  "Keyboard shortcut settings": "键盘快捷键设置",
  "In chats": "在对话中",
  "Send message": "发送消息",
  "New line in message": "消息内换行",
  "Toggle extended thinking": "切换深度思考",
  "Upload file": "上传文件",
  "Stop Claude’s response": "停止 Claude 的回复",
  "Add": "添加",
  "Not connected": "未连接",
  "BETA": "测试版",
  "Connect Claude to your data and tools.": "将 Claude 连接到您的数据和工具。",
  "Learn more about connectors": "进一步了解连接器",
  "or get started with": "或着手于",
  "pre-built ones": "预构建的连接器",
  "Name": "名称",
  "Remote MCP server URL": "远程 MCP 服务器 URL",
  "Advanced settings": "高级设置",
  "OAuth Client ID (optional)": "OAuth 客户端 ID（可选）",
  "OAuth Client Secret (optional)": "OAuth 客户端密钥（可选）",
  "Only use connectors from developers you trust. Anthropic does not control which tools developers make available and cannot verify that they will work as intended or that they won't change.": "仅使用来自您信任的开发者的连接器。Anthropic 不控制开发者提供的工具，也无法验证它们是否按预期工作或是否会发生更改。",
  "Building an MCP server?": "正在构建 MCP 服务器？",
  "Report issues and subscribe to updates here": "在此处报告问题并订阅更新。",
  "Plugins": "插件",
  "Directory": "目录",
  "Search connectors…": "搜索连接器…",
  "Anthropic & Partners": "Anthropic 与合作伙伴",
  "Search connectors...": "搜索连接器...",
  "Filter by": "筛选依据",
  "Anthropic & Partners": "Anthropic 及合作伙伴",
  "Type": "类型",
  "Interactive": "交互式",
  "Web": "网页",
  "Category": "类别",
  "business-productivity": "商务办公",
  "commerce-shopping": "商业购物",
  "Communication": "通讯",
  "Data": "数据",
  "Financial services": "金融服务",
  "Health": "健康",
  "Life sciences": "生命科学",
  "Productivity": "生产力",
  "Sales and marketing": "销售与市场",
  "Most popular": "最热门",
  "Trending": "趋势中",
  "Interactive": "交互式",
  "Let Claude access your filesystem to read and write files.": "允许 Claude 访问您的文件系统进行读写操作。",
  "Read, annotate, and interact with PDF files — interactive viewer with search, navigation, annotations, form filling, and text extraction": "阅读、标注 PDF 并与之交互 —— 具备搜索、导航、批注、表单填写及文本提取功能的交互式查看器",
  "Control Google Chrome browser tabs, windows, and navigation": "控制 Google Chrome 浏览器的标签页、窗口和导航",
  "Control Microsoft PowerPoint with AppleScript automation": "通过 AppleScript 自动化控制 Microsoft PowerPoint",
  "Control Microsoft Word with AppleScript automation": "通过 AppleScript 自动化控制 Microsoft Word",
  "Extract data from any website with thousands of scrapers, crawlers, and automations on Apify Store.": "利用 Apify 商店中数以千计的爬虫和自动化工具从任何网站提取数据。",
  "MCP Server that enables Claude to interact with Windows OS": "支持 Claude 与 Windows 操作系统交互的 MCP 服务器",
  "Stocks, options & indices market data via Massive.com financial data API. Access real-time and historical prices, quotes, trades, and aggregates for equities, options contracts, ETFs, FX, crypto, and more.": "通过 Massive.com 获取股票、期权及指数市场数据。访问股票、期权合约、ETF、外汇、加密货币等的实时与历史价格、报价及交易信息。",
  "The Figma MCP server helps you pull in Figma context and generate high-quality code that aligns with your codebase and design intent.": "Figma MCP 服务器可帮助您引入 Figma 上下文，并生成符合代码库和设计意图的高质量代码。",
  "MCP server for interacting with Kubernetes clusters via kubectl": "通过 kubectl 与 Kubernetes 集群交互的 MCP 服务器",
  "Read events and tasks, create new items, make basic edits, and delete items from Fantastical for Mac.": "在 Mac 版 Fantastical 中阅读事件和任务、创建新项目、进行基本编辑及删除项目。",
  "Read, write, and manage notes in Apple Notes": "在 Apple Notes 中阅读、写入并管理笔记",
  "A full local PDF workflow for Claude: interactive viewing, form filling with reusable profiles, page organization, extraction, and analysis — far beyond basic PDF reading.": "Claude 的全套本地 PDF 工作流：交互式查看、使用可复用配置文件填写表单、页面整理、提取与分析 —— 远超基础 PDF 阅读功能。",
  "Execute AppleScript to automate tasks on macOS.": "执行 AppleScript 以自动执行 macOS 上的任务。",
  "MCP server for interacting with the Drafts app on macOS": "与 macOS 版 Drafts 应用交互的 MCP 服务器",
  "Send emails and manage templates using Mailtrap": "使用 Mailtrap 发送电子邮件并管理模板",
  "Connect data from hundreds of data sources and apps to analyze it with Claude.": "连接来自数百个数据源和应用的数据，并使用 Claude 进行分析。",
  "Control web browsers through the Model Context Protocol using Chrome DevTools": "通过 Chrome DevTools 利用 MCP 协议控制 Web 浏览器",
  "Gene set enrichment analysis using Enrichr API with multi-library support": "使用支持多库的 Enrichr API 进行基因集富集分析",
  "Analyze, search, and extract structured data from video collections using Cloudglue's video understanding platform.": "利用 Cloudglue 的视频理解平台对视频集进行分析、搜索及提取结构化数据。",
  "The AWS API MCP Server lets AI assistants manage AWS resources using AWS CLI commands. It acts as a secure bridge, enabling creation, updates, and management across all AWS services.": "AWS API MCP 服务器允许 AI 助手使用 AWS CLI 命令管理 AWS 资源。它作为一个安全桥梁，支持跨所有 AWS 服务的创建、更新和管理操作。",
  "Socket MCP server for scanning dependencies": "用于扫描依赖项的 Socket MCP 服务器",
  "Build, explore, and automate on your local machine with access to files and terminal.": "通过访问文件和终端，在本地机器上进行构建、探索和自动化。",
  "A high-performance MCP server for Metabase analytics data access with response optimization and robust error handling.": "用于 Metabase 分析数据访问的高性能 MCP 服务器，具备响应优化和健壮的错误处理能力。",
  "Helping agents see and understand data.": "助力代理查看并理解数据。",
  "Cloudinary Asset Management MCP Server": "Cloudinary 资产管理 MCP 服务器",
  "Create a website in seconds! Generate, design, write code, and write copy for your website. Powered by B12.": "几秒钟内创建网站！为您的网站生成设计、编写代码和文案。由 B12 提供支持。",
  "Send, read, and manage messages through Apple's Messages app": "通过 Apple 的信息应用发送、阅读并管理消息",
  "Generate and adapt SAP Fiori elements applications with AI coding assistants. Supports List Report, Object Page, and Flexible Column layouts.": "利用 AI 编程助手生成并适配 SAP Fiori 元素应用。支持列表报告、对象页面及灵活列布局。",
  "Power your chat with B2B data to create lead lists, research companies, personalize your outreach, and more.": "利用 B2B 数据强化对话，创建潜在客户列表、研究公司、个性化外联等。",
  "MCP server for SAPUI5/OpenUI5 development. Create and validate apps, access API docs, and get development guidelines.": "用于 SAPUI5/OpenUI5 开发的 MCP 服务器。创建并验证应用，访问 API 文档及获取开发指南。",
  "Docling MCP Server - Document processing and analysis capabilities such as creation and manipulation": "Docling MCP 服务器 —— 提供文档处理和分析能力，如创建与操作",
  "Zscaler MCP Server provides AI-powered management of Zscaler Zero Trust Exchange services including ZIA, ZPA, ZDX, ZCC, ZTW, ZIdentity, EASM, and Z-Insights": "Zscaler MCP 服务器提供对 Zscaler 零信任交换服务的 AI 驱动管理，包括 ZIA、ZPA、ZDX 等。",
  "Record meetings and voice memos, transcribe locally with whisper.cpp, search across everything. 24 tools, fully offline. Nothing leaves your machine.": "记录会议和语音备忘录，使用 whisper.cpp 在本地转录，支持全局搜索。24 种工具，完全离线。数据不离开您的机器。",
  "MCP server for interacting with the NotePlan app on macOS": "与 macOS 版 NotePlan 应用交互的 MCP 服务器",
  "ToolUniverse: An ecosystem for democratizing AI scientists with 600+ scientific tools.": "ToolUniverse：一个拥有 600 多种科学工具的生态系统，旨在使 AI 科学家大众化。",
  "Audio Player MCP Bundle with ElevenLabs integration. Generate speech, sound effects, and music using the ElevenLabs API, or play any local audio file.": "集成 ElevenLabs 的音频播放器 MCP 包。使用 ElevenLabs API 生成语音、音效和音乐，或播放任何本地音频文件。",
  "Lightweight MCP Server for macOS desktop interaction": "用于 macOS 桌面交互的轻量级 MCP 服务器",
  "Send push notifications with personalized sounds via the Vybit platform": "通过 Vybit 平台发送带有个性化声音的推送通知",
  "Connect AI agents to your Intent Layer. Get strategic context, dependency graphs, and implementation prompts.": "将 AI 代理连接到您的意图层（Intent Layer）。获取战略上下文、依赖图及实现提示词。",
  "MCP Server for interacting with GrowthBook - an open source feature flagging and experimentation platform": "与开源功能旗标及实验平台 GrowthBook 交互的 MCP 服务器",
  "Create and manage ElevenLabs Agents with an interactive UI. Build conversational AI agents with custom voices, personalities, and behaviors.": "通过交互式 UI 创建并管理 ElevenLabs 代理。构建具有自定义语音、性格和行为的对话式 AI 代理。",
  "A Model Context Protocol (MCP) server for shadcn/ui components, providing AI assistants with access to component source code, demos, blocks, and metadata.": "shadcn/ui 组件的 MCP 服务器，为 AI 助手提供对组件源码、示例、区块及元数据的访问。",
  "An MCP server giving access to Grafana dashboards, datasources, alerting, and more": "提供 Grafana 仪表板、数据源、告警等访问权限的 MCP 服务器",
  "Semantic codebase search for Claude Desktop. Find code by meaning, not just keywords. Zero API keys, zero setup.": "Claude 桌面版的语义代码库搜索。按含义而非仅按关键词查找代码。无需 API 密钥，零配置。",
  "Give Claude full access to Jaz accounting. Create invoices, record bills, reconcile banks, close books, compute taxes, and generate reports.": "赋予 Claude 对 Jaz 财务系统的完整访问权限。创建发票、记录账单、对账、结账、计算税费及生成报告。",
  "Access near real-time public health data from PopHIVE dashboards including immunizations, respiratory diseases, chronic conditions, hospital capacity, injury/overdose rates, and youth mental health trends.": "访问来自 PopHIVE 仪表板的近实时公共卫生数据，包括疫苗接种、呼吸系统疾病、慢性病、医院容量、受伤/用药过量率及青少年心理健康趋势。",
  "AI-assisted development of SAP Mobile Development Kit (MDK) applications. Create, validate, migrate, and deploy cross-platform mobile apps.": "AI 辅助的 SAP 移动开发工具包 (MDK) 应用开发。创建、验证、迁移并部署跨平台移动应用。",
  "Explore open data portals based on CKAN (dati.gov.it, data.gov, open.canada.ca, ...)": "探索基于 CKAN 的开放数据门户（如 data.gov 等）",
  "Smarter Workflows for Files and Signatures": "更智能的文件与签名工作流",
  "Spend more time on your craft by automating repetitive tasks with Claude and Affinity": "通过 Claude 和 Affinity 自动化重复任务，将更多时间投入到核心创作中",
  "Braze MCP Server - Model Context Protocol server for Braze REST API Read-Only endpoints access": "Braze MCP 服务器 —— 用于访问 Braze REST API 只读端点的服务器",
  "Interact with 10x Genomics Cloud platform": "与 10x Genomics 云平台交互",
  "Lightweight MCP Server for Android Operating System": "用于 Android 操作系统的轻量级 MCP 服务器",
  "MCP Instana Server for Observability": "用于可观测性的 MCP Instana 服务器",
  "MCP server for MeetGeek API integration, providing tools to manage meetings, transcripts, highlights, and insights.": "用于 MeetGeek API 集成的 MCP 服务器，提供管理会议、转录文本、高亮及洞察的工具。",
  "Model Context Protocol tools for Vendr software pricing insights. Get price estimates, company information, and product catalog data.": "用于 Vendr 软件定价洞察的 MCP 工具。获取价格预估、公司信息及产品目录数据。",
  "Free blockchain data access across 60+ networks. Live lookups for balances, transactions, blocks, tokens, staking, governance, and domain resolution.": "跨 60 多个网络的免费区块链数据访问。实时查询余额、交易、区块、代币、质押、治理及域名解析。",
  "Manage your calendars, events, tasks, and availability in BusyCal.": "在 BusyCal 中管理您的日历、事件、任务及忙闲状态。",
  "Access Dynatrace observability data: logs, metrics, problems, vulnerabilities via DQL and Dynatrace Intelligence": "通过 DQL 和 Dynatrace Intelligence 访问 Dynatrace 可观测性数据：日志、指标、问题、漏洞",
  "Multiple data science tools for data loading, cleaning, visualization, and ML workflows": "用于数据加载、清洗、可视化及机器学习工作流的多种数据科学工具",
  "Connect to Sketch's local MCP server to explore your designs, organize your documents, generate code, export assets, and more.": "连接到 Sketch 的本地 MCP 服务器以探索您的设计、整理文档、生成代码、导出资产等。",
  "Check balances, view orders, analyze markets, and backtest trading strategies on Revolut X. All through natural language in Claude.": "在 Revolut X 上检查余额、查看订单、分析市场及回测交易策略。全部通过 Claude 的自然语言实现。",
  "Provide real-time geospatial context from TomTom - including maps, routing, search geocoding and traffic.": "提供来自 TomTom 的实时地理空间上下文 —— 包括地图、路由、搜索地理编码及流量信息。",
  "Manage Palo Alto Networks firewalls and Panorama with 116 tools — read system state, security policies, logs, VPN status, and more.": "使用 116 种工具管理 Palo Alto 网络防火墙和 Panorama —— 读取系统状态、安全策略、日志、VPN 状态等。",
  "MCP server for Tomba email finder and verification API": "用于 Tomba 邮箱查找和验证 API 的 MCP 服务器",
  "Access your Defense.com portal to view open threats, security issues, and team workload": "访问您的 Defense.com 门户以查看开放威胁、安全问题及团队工作负载",
  "AI-assisted development of SAP Cloud Application Programming Model (CAP) projects. Enables searching CDS models and CAP documentation.": "AI 辅助的 SAP 云应用编程模型 (CAP) 项目开发。支持搜索 CDS 模型及 CAP 文档。",
  "Search and browse documentation from Dash, the macOS API documentation browser.": "通过 macOS API 文档浏览器 Dash 搜索并浏览文档。",
  "MCP server for Miggo's public API - query services, endpoints, vulnerabilities, findings, dependencies, and third-party integrations": "用于 Miggo 公开 API 的 MCP 服务器 —— 查询服务、端点、漏洞、发现、依赖项及第三方集成",
  "Model Context Protocol server that orchestrates SignWell's e-signature workflows — create, send, track, and manage documents and templates.": "编排 SignWell 电子签名工作流的 MCP 服务器 —— 创建、发送、跟踪并管理文档与模板。",
  "MCP server for RT (Request Tracker) — search tickets, manage queues, add comments and replies, and update ticket fields.": "用于 RT (Request Tracker) 的 MCP 服务器 —— 搜索工单、管理队列、添加评论与回复及更新工单字段。",
  "Expose Conviso Platform data (companies, projects, issues, assets, metrics) to MCP clients.": "向 MCP 客户端展示 Conviso 平台数据（公司、项目、问题、资产、指标）。",
  "Understand and troubleshoot your Journeys and Campaigns": "了解并排查您的客户旅程和营销活动。",
  "Search, read, and upload files instantly": "即时搜索、阅读并上传文件",
  "Manage your schedule and coordinate meetings effortlessly": "轻松管理您的日程并协调会议。",
  "Draft replies, summarize threads, & search your inbox": "起草回复、总结邮件往来并搜索您的收件箱。",
  "Track and analyze your finances with Digits": "使用 Digits 跟踪并分析您的财务状况。",
  "Turn feedback into decisions": "将反馈转化为决策",
  "Analyze U.S. fixed income trade and reference data": "分析美国固定收益交易及参考数据。",
  "Your meetings, now part of every Claude conversation": "让您的会议记录成为 Claude 对话的一部分",
  "Drive your email and calendar, right from Claude": "直接在 Claude 中驱动您的电子邮件和日历",
  "Search and explore regulated software lifecycle data": "搜索并探索受监管的软件生命周期数据",
  "Analyze your brand's visibility across LLMs": "分析您的品牌在各大 LLM 中的可见度",
  "Manage projects, boards, and workflows in monday.com": "在 monday.com 中管理项目、看板和工作流。",
  "Chat with your CRM data to get personalized insights": "与您的 CRM 数据对话以获取个性化洞察。",
  "Manage issues, projects & team workflows in Linear": "在 Linear 中管理议题、项目和团队工作流。",
  "Access to Intercom data for better customer insights": "访问 Intercom 数据以获取更佳的客户洞察。",
  "Access Jira & Confluence from Claude": "从 Claude 访问 Jira 和 Confluence。",
  "Generate diagrams and better code from Figma context": "根据 Figma 上下文生成图表和更优质的代码。",
  "Search, access and get insights on your Box content": "搜索、访问并获取您的 Box 内容洞察。",
  "Search, recap, and act on your Zoom meetings": "搜索、回顾并跟进您的 Zoom 会议。",
  "Search, create, autofill, and export Canva designs": "搜索、创建、自动填充并导出 Canva 设计。",
  "Connect your Notion workspace to search, update, and power workflows across tools": "连接您的 Notion 工作区，以实现跨工具的搜索、更新和流程驱动。",
  "Access your company's SharePoint, OneDrive, Outlook, and Teams directly in Claude": "直接在 Claude 中访问公司的 SharePoint、OneDrive、Outlook 和 Teams。",
  "Access and create new content on Miro boards": "访问并在 Miro 看板上创建新内容。",
  "Ideate, diagram, and align teams": "构思、绘图并达成团队共识。",
  "Send messages, create canvases, and fetch Slack data": "发送消息、创建画布并获取 Slack 数据。",
  "Bring your structured data to Claude": "将您的结构化数据引入 Claude。",
  "Discover local food spots and order with a conversation": "通过对话发现当地美食并下单。",
  "Connect Claude to NetSuite data for analysis & insights": "将 Claude 连接到 NetSuite 数据以获取分析与洞察。",
  "Automate workflows across thousands of apps via conversation": "通过对话在数千个应用间自动化工作流。",
  "The AI notepad for meetings": "会议专用的 AI 笔记本",
  "Credit score factors & insights": "信用评分因素与洞察",
  "Connect to Asana to coordinate tasks, projects, and goals": "连接至 Asana 以协调任务、项目和目标。",
  "Analyze and manage Smartsheet data with Claude": "使用 Claude 分析并管理 Smartsheet 数据。",
  "Create marketing campaigns": "创建营销活动",
  "Get insights from your autonomous AI analyst": "从您的自主 AI 分析师处获取洞察。",
  "Search trusted Microsoft docs to power your development": "搜索受信任的微软文档以助力您的开发。",
  "Access ClinicalTrials.gov data": "访问 ClinicalTrials.gov 数据",
  "Connect AI tools securely to your GitLab data": "安全地将 AI 工具连接到您的 GitLab 数据。",
  "Create presentations, docs, socials, and sites with AI": "使用 AI 创建演示文稿、文档、社交内容和网站。",
  "Find funders who support causes like yours": "寻找支持您这类事业的资助者。",
  "Access ICD-10-CM and ICD-10-PCS code sets": "访问 ICD-10-CM 和 ICD-10-PCS 代码集",
  "Intelligent, secure contract management by Docusign": "由 Docusign 提供的智能安全合同管理",
  "Search, query, and debug errors intelligently": "智能搜索、查询并调试错误",
  "See and manage everything in incident.io": "在 incident.io 中查看并管理一切",
  "Enrich contacts & accounts with GTM intelligence": "利用 GTM 情报丰富联系人和账户信息",
  "Find people, productivity and business impact insights": "查找人员、生产力及业务影响洞察",
  "Access the CMS Coverage Database": "访问 CMS 覆盖范围数据库",
  "Access US National Provider Identifier (NPI) Registry": "访问美国国家提供者识别码 (NPI) 注册中心",
  "Access bioRxiv and medRxiv preprint data": "访问 bioRxiv 和 medRxiv 预印本数据",
  "PitchBook data, embedded in the way you work.": "将 PitchBook 数据嵌入到您的工作方式中。",
  "Analyze, debug, and manage projects and deployments": "分析、调试并管理项目和部署。",
  "Pharmaceutical drug & clinical trial intelligence": "制药及临床试验情报",
  "Analyze, query, and manage your Mixpanel data": "分析、查询并管理您的 Mixpanel 数据。",
  "Access the ChEMBL Database": "访问 ChEMBL 数据库",
  "SEO & AI search analytics": "SEO 与 AI 搜索分析",
  "Manage databases, authentication, and storage": "管理数据库、身份验证和存储。",
  "Experience analytics platform for digital businesses": "数字业务的体验分析平台",
  "Clean Public Equity Fundamental Data": "干净的公共股本基本面数据",
  "Project management & collaboration for teams & agents": "团队与代理的项目管理与协作",
  "Unleash your team's best performance with Outreach AI": "利用 Outreach AI 释放团队的最佳效能",
  "Web Search + Code Docs Search": "网络搜索 + 代码文档搜索",
  "Manage incidents, services and on-call schedules": "管理事件、服务和排班表",
  "Retrieve both structured and unstructured data": "检索结构化和非结构化数据",
  "The AI platform for recruiting.": "用于招聘的 AI 平台。",
  "Validates Mermaid syntax, renders diagrams as high-quality SVG, and displays them instantly in an interactive UI where users can preview, zoom, and iterate in real time.": "验证 Mermaid 语法，将图表渲染为高质量 SVG，并在交互式 UI 中即时显示，支持实时预览、缩放和迭代。",
  "Give API context to your coding agents": "为您的编程代理提供 API 上下文",
  "MCP for creating interactive hand-drawn diagrams in Excalidraw": "用于在 Excalidraw 中创建交互式手绘图表的 MCP",
  "Connect, control, and automate 1,000+ apps with IFTTT": "通过 IFTTT 连接、控制并自动化 1,000 多个应用",
  "Connect to Pendo for product and user insights": "连接到 Pendo 以获取产品和用户洞察",
  "Ask AI about your sales calls, deals & pipeline": "向 AI 咨询关于销售电话、交易及管道的情况",
  "Find prospects. Research accounts. Personalize outreach": "寻找潜在客户、研究账户并个性化外联。",
  "BigQuery: Advanced analytical insights for agents": "BigQuery：为代理提供的高级分析洞察",
  "Manage event types, availability, and bookings.": "管理事件类型、空闲状态及预订。",
  "Payment processing and financial infrastructure tools": "支付处理及金融基础设施工具",
  "Access and run your n8n workflows": "访问并运行您的 n8n 工作流",
  "Bring enterprise context to Claude and your AI tools": "将企业上下文引入 Claude 和您的 AI 工具",
  "Search biomedical literature from PubMed": "从 PubMed 搜索生物医学文献",
  "Find buyers. Book more meetings. Close more deals.": "寻找买家。预约更多会议。成交更多交易。",
  "Search for jobs on Indeed": "在 Indeed 上搜索工作",
  "Managed MCP servers with Unity Catalog and Mosaic AI": "使用 Unity Catalog 和 Mosaic AI 管理的 MCP 服务器",
  "Build GoCardless payment API integrations": "构建 GoCardless 支付 API 集成",
  "Search, access, and analyze your Ramp financial data": "搜索、访问并分析您的 Ramp 财务数据",
  "Analyze and generate insights from meeting transcripts": "从会议转录文本中分析并生成洞察",
  "Power AI Workflows with Customer Context": "利用客户上下文增强 AI 工作流",
  "Event platform for managing tickets, orders & more": "用于管理门票、订单等的活动平台",
  "Query a range of S&P Global datasets": "查询一系列 S&P Global 数据集",
  "Analyze business data": "分析业务数据",
  "Up-to-date docs for LLMs and AI code editors": "为 LLM 和 AI 代码编辑器提供最新的文档",
  "Analyze client conversations, patterns, and insights.": "分析客户对话、模式及洞察。",
  "Search government procurement & spending data": "搜索政府采购及支出数据",
  "Access the Hugging Face Hub and thousands of Gradio Apps": "访问 Hugging Face 枢纽及数千个 Gradio 应用",
  "Manage Webflow CMS, pages, assets and sites": "管理 Webflow 内容管理系统、页面、资产和站点",
  "Business Finances made simple": "让业务财务变得简单",
  "Build applications with compute, storage, and AI": "利用计算、存储及 AI 构建应用",
  "Manage and automate your support tickets": "管理并自动化您的支持工单",
  "Secure AI access to manage your WordPress.com sites": "通过安全 AI 访问来管理您的 WordPress.com 站点",
  "Find and enrich B2B contacts and companies": "查找并丰富 B2B 联系人及公司信息",
  "Securely deploy servers in a matter of seconds in Tines": "在 Tines 中数秒内安全部署服务器",
  "Connect 325+ marketing, analytics and CRM data sources": "连接 325 多个营销、分析及 CRM 数据源",
  "Query, analyze, and manage your PostHog insights": "查询、分析并管理您的 PostHog 洞察",
  "Get answers from unified feedback of your customers.": "从客户的统一反馈中获取答案。",
  "Search and explore skill-building resources": "搜索并探索技能提升资源",
  "Access institutional-quality financial data and analytics": "访问机构级金融数据和分析",
  "Bring real buyer signals into AI workflows": "将真实的买家信号引入 AI 工作流",
  "Manage your Adobe Experience Manager content": "管理您的 Adobe Experience Manager 内容",
  "Turn AI insights into documents": "将 AI 洞察转化为文档",
  "Run Make scenarios and manage your Make account": "运行 Make 场景并管理您的 Make 帐户",
  "Query your data using natural language through Omni's semantic model": "通过 Omni 的语义模型利用自然语言查询您的数据",
  "Analyze marketing performance across 200+ platforms": "分析跨 200 多个平台的营销表现",
  "Answer legal queries, search vaults, and research": "回答法律咨询、搜索保管库并进行研究",
  "Explore scientific research": "探索科学研究",
  "Search and interact with your company knowledge": "搜索并与您的公司知识库交互",
  "Search and update your company's knowledge graph": "搜索并更新您的公司知识图谱",
  "Intelligent finance automation": "智能财务自动化",
  "Craft content that wins AI search": "打造在 AI 搜索中脱颖而出的内容",
  "Answer questions with the Hex agent": "通过 Hex 代理回答问题",
  "Report, strategize & create with real-time Klaviyo data": "利用实时 Klaviyo 数据进行报告、制定策略及创作",
  "Explore customer data and generate insights via Claude": "通过 Claude 探索客户数据并生成洞察",
  "Save money on Software + AI contracts": "在软件和 AI 合约上节省费用",
  "Create, deploy, manage, and secure websites on Netlify.": "在 Netlify 上创建、部署、管理并保护网站。",
  "Real time web, mobile app, and market data.": "实时的网页、移动应用及市场数据。",
  "Discover, evaluate, and buy solutions for the cloud": "发现、评估并购买云解决方案",
  "Predictive intelligence on private companies": "关于私营公司的预测性情报",
  "Search domains and check availability": "搜索域名并检查可用性",
  "Turn data into insight": "将数据转化为洞察",
  "Find company & contact data": "查找公司及联系人数据",
  "Manage and build sites and apps on Wix": "在 Wix 上管理并构建站点与应用",
  "Explore partner data and ecosystem insights in Claude": "在 Claude 中探索合作伙伴数据及生态系统洞察",
  "Access and analyze blockchain data": "访问并分析区块链数据",
  "Zoho Desk MCP for Customer Support Automation": "用于客户支持自动化的 Zoho Desk MCP",
  "Automate workflows and connect your business apps": "自动化工作流并连接您的业务应用",
  "Financial fundamental data and KPIs with hyperlinks": "带有超链接的财务基本面数据及关键绩效指标",
  "Enhance responses with scholarly research and citations": "通过学术研究和引用来增强回答效果",
  "Zoho Books MCP for Smart Finance Ops": "用于智能财务运营的 Zoho Books MCP",
  "Search for and use scientific templates and icons": "搜索并使用科学模板及图标",
  "Zoho Projects MCP for Task & Project Automation": "用于任务和项目自动化的 Zoho Projects MCP",
  "Create, query, and manage structured content in Sanity": "在 Sanity 中创建、查询并管理结构化内容",
  "Create forms & analyze submissions inside Claude": "在 Claude 内部创建表单并分析提交内容",
  "MCP Server for Zoho CRM Workflows": "用于 Zoho CRM 工作流的 MCP 服务器",
  "Conduct legal research and create work product": "开展法律研究并创建工作成果",
  "Up-to-date investment and market insights": "最新的投资和市场洞察",
  "Search, manage, and update your Attio CRM from Claude": "从 Claude 搜索、管理并更新您的 Attio CRM",
  "Chat with your meetings to uncover actionable insights": "与您的会议记录对话以发现可落地的洞察",
  "Connect your AI agents to the web": "将您的 AI 代理连接到网络",
  "Demo PDF viewer that renders PDFs from allowed URLs like arxiv.org": "演示用 PDF 查看器，支持渲染来自允许的 URL（如 arxiv.org）的 PDF",
  "Search pg and Tiger docs, learn database skills": "搜索 pg 和 Tiger 文档，学习数据库技能",
  "Access PayPal payments platform": "访问 PayPal 支付平台",
  "Financial data and AI infrastructure for company research.": "用于公司研究的金融数据和 AI 基础设施。",
  "Add your meetings context via transcripts and notes": "通过转录文本和笔记添加会议上下文",
  "Integrate with the Airwallex Platform using Claude": "使用 Claude 集成至 Airwallex 平台",
  "Search flights in Claude": "在 Claude 中搜索航班",
  "Build and manage Base44 apps": "构建并管理 Base44 应用",
  "Estimate tax refunds and connect with live tax experts": "估算退税并联系在线税务专家",
  "Securely access and analyze Egnyte content": "安全地访问并分析 Egnyte 内容",
  "Let Claude sketch, draw, and diagram with you": "让 Claude 与您一起素描、绘画和绘图",
  "Search and access context from meetings": "搜索并访问会议上下文",
  "Search and manage Pylon support issues": "搜索并管理 Pylon 支持问题",
  "Your GTM Copilot": "您的 GTM 副驾驶",
  "Risk insights, analytics, and decision intelligence": "风险洞察、分析及决策情报",
  "Query and explore observability data and SLOs": "查询并探索可观测性数据及服务水平目标 (SLO)",
  "Compare hotels, then book direct": "比较酒店，然后直接预订",
  "Estimate your federal & state taxes with Aiwyn's tax engine": "使用 Aiwyn 的税务引擎估算您的联邦税和州税",
  "Connect and use PlayMCP servers in your toolbox": "在工具箱中连接并使用 PlayMCP 服务器",
  "Securely retrieve data from your federated data sources": "从您的联邦数据源中安全地检索数据",
  "Search, analyze, and export Campfire data": "搜索、分析并导出 Campfire 数据",
  "A universal concierge for complex businesses": "面向复杂业务的通用礼宾服务",
  "Managed MCP platform for 350 sources": "支持 350 个源的管理型 MCP 平台",
  "Drug target discovery and prioritisation platform": "药物靶点发现及优先级排序平台",
  "Real time prices, orders, charts, and more for crypto": "加密货币的实时价格、订单、图表等",
  "Search, compare and book flights, dynamic packages (flight + hotel) and hotels across global airlines and hotel suppliers.": "在全球航空公司和酒店供应商中搜索、比较并预订航班、动态套餐（机 + 酒）和酒店。",
  "Connect Claude to Close CRM to securely access and act on your sales data": "将 Claude 连接至 Close CRM 以安全访问并操作您的销售数据",
  "Query and analyze your Gusto data": "查询并分析您的 Gusto 数据",
  "Shorten links, generate QR Codes, and track performance": "缩短链接、生成二维码并跟踪表现",
  "Marketing campaign and audience insights from Adobe": "来自 Adobe 的营销活动及受众洞察",
  "India's official statistics via natural language": "通过自然语言获取印度官方统计数据",
  "Ask Claude to generate and play some sheet music for you with a visual component": "让 Claude 为您生成并播放带视觉组件的乐谱",
  "Interact with your Chronograph data directly in Claude": "直接在 Claude 中与您的 Chronograph 数据交互",
  "Discuss and iterate on Magic Patterns designs": "讨论并迭代 Magic Patterns 设计",
  "Find your ideal hotel at the best price.": "以最优价格寻找您的理想酒店。",
  "Access best in class data & analytics across a broad spectrum of asset classes.": "跨广泛资产类别访问一流的数据和分析。",
  "Find active tech jobs on Dice": "在 Dice 上查找活跃的技术职位",
  "Discover, research, and enrich companies and people": "发现、研究并丰富公司和人员信息",
  "Demo 3D viewer that renders interactive 3D scenes and models using Three.js": "演示用 3D 查看器，支持使用 Three.js 渲染交互式 3D 场景和模型",
  "Record screen and collect automatic context for issues": "录制屏幕并自动收集问题的上下文信息",
  "Access business data from hundreds of sources": "访问来自数百个源的业务数据",
  "Search, analyze and understand your finances on Mercury": "在 Mercury 上搜索、分析并理解您的财务状况",
  "K-12 standards, skills, and learning progressions": "K-12 标准、技能及学习进度",
  "The AI notebook for everything on your mind": "记录您脑中一切想法的 AI 笔记本",
  "Research nonprofits and funders using Candid's data": "利用 Candid 的数据研究非营利组织和出资人",
  "Clinical trial software and site ranking tools": "临床试验软件及站点排名工具",
  "Autonomous marketing to transform how you work": "通过自主营销改变您的工作方式",
  "Manage, transform and deliver your images & videos": "管理、转换并交付您的图像和视频",
  "Trusted real-time global financial news provider": "值得信赖的实时全球财经新闻提供商",
  "Access real-time financial data": "访问实时金融数据",
  "Search and manage transaction, merchant, and payment data": "搜索并管理交易、商户及支付数据",
  "Turn Claude into your email marketing assistant": "将 Claude 变为您的邮件营销助手",
  "Automate eSignature workflows directly from Claude": "直接从 Claude 中自动化电子签名工作流",
  "Add authentication, organizations, and billing": "添加身份验证、组织和计费功能",
  "Query your CRM. Create records. Ask anything.": "查询您的 CRM。创建记录。咨询任何问题。",
  "Attorney guidance & tools for business & personal needs": "面向商业和个人需求的律师指导与工具",
  "Notes & second brain": "笔记与第二大脑",
  "Monitor, debug, and optimize your Plaid integration": "监控、调试并优化您的 Plaid 集成",
  "Search and metadata tools for Synapse scientific data": "用于 Synapse 科学数据的搜索和元数据工具",
  "Real-time Yardi data & insights": "实时的 Yardi 数据与洞察",
  "Add real-time social media data to your searches": "在搜索中添加实时社交媒体数据",
  "Access all your internal tools, enterprise apps & data.": "访问您所有的内部工具、企业应用及数据。",
  "Get answers from your data": "从您的数据中获取答案",
  "Interact with AI agents built for biology": "与专为生物学构建的 AI 代理交互",
  "Discover every grant opportunity in existence.": "发现现有的每一个资助机会。",
  "From query to qualified lead in seconds.": "数秒内从查询转为合格的潜在客户。",
  "MCP server for Google Compute Engine": "用于 Google Compute Engine 的 MCP 服务器",
  "Live events, filings, company publications, and more": "现场活动、申报文件、公司出版物等",
  "Secure, production-ready AI orchestration for privacy": "用于隐私保护的安全、生产就绪型 AI 编排",
  "Know everything about your prospects & customers with CRMxL": "通过 CRMxL 了解关于您潜在客户及现有客户的一切",
  "AI visibility and local search intelligence platform": "AI 可见度及本地搜索智能平台",
  "Turn Claude into your Razorpay Dashboard Assistant": "将 Claude 变为您的 Razorpay 仪表板助手",
  "Sign, send & manage documents with DocuSeal": "使用 DocuSeal 签名、发送并管理文档",
  "Authenticated access to your Postgres and MySQL DB's": "对 Postgres 和 MySQL 数据库的身份验证访问",
  "Search your context lake and safely run actions": "搜索您的上下文湖并安全地执行操作",
  "Company intelligence & workforce analytics": "公司情报及劳动力分析",
  "Find and engage with verified nonprofits": "查找并参与经过认证的非营利组织活动",
  "Connect to R&D data, source experiments, and notebooks": "连接至研发数据、源实验及笔记本",
  "Manage documents, send signature requests, and convert Markdown to PDF": "管理文档、发送签名请求并将 Markdown 转换为 PDF",
  "Manage your Stytch Project": "管理您的 Stytch 项目",
  "Simulate fund classifications under proposed SFDR 2.0": "在拟议的 SFDR 2.0 下模拟基金分类",
  "Browse music charts & your personalized music picks": "浏览音乐榜单及您的个性化音乐推荐",
  "Search for US Government Contracting Data": "搜索美国政府合同数据",
  "Explore and update your Process Street data": "探索并更新您的 Process Street 数据",
  "Discover the right Wyndham Hotel for you, faster": "更快速地发现适合您的 Wyndham 酒店",
  "Search Apollo docs, specs, and best practices": "搜索 Apollo 文档、规范和最佳实践",
  "Discover live entertainment events worldwide": "发现全球现场娱乐活动",
  "High-quality translation with human verification": "带人工验证的高质量翻译",
  "One connection to access all your tools securely": "一个连接即可安全访问您的所有工具",
  "Securely, compliantly access Intapp Celeste products": "安全、合规地访问 Intapp Celeste 产品",
  "Analyze and get insights from your lakehouse datahouse data": "从您的湖仓数据中分析并获取洞察",
  "Search, access, and get insights on your Amplitude data": "搜索、访问并获取您的 Amplitude 数据洞察",
  "Know everything about your prospects & customers with CRMxL": "借助 CRMx，全面了解您的潜在客户和现有客户。",
  "Analyze and get insights from your lakehouse data": "分析并从您的数据湖仓一体中获取见解",
  "Manage Palo Alto Networks firewalls and Panorama with 116 tools — read system state, security policies, logs, VPN status, and more. Supports configuration changes with staged commits. Connect using just a hostname and API key."  : "使用 116 种工具管理 Palo Alto Networks 防火墙和 Panorama，包括读取系统状态、安全策略、日志、VPN 状态等。支持分阶段提交配置更改。只需主机名和 API 密钥即可连接。",
  "Free blockchain data access across 60+ networks. Live lookups for balances, transactions, blocks, tokens, staking, governance, and domain resolution — powered by Pocket Network's decentralized RPC infrastructure. No API key required.": "免费访问 60 多个区块链网络的数据。实时查询余额、交易、区块、代币、质押、治理和域名解析——由 Pocket Network 的去中心化 RPC 基础设施提供支持。无需 API 密钥。",
  "Default": "默认",
  "Popular": "最受欢迎",
  "Trending": "趋势中",
  "Alphabetical": "按首字母排序",
  "You are not connected to GitHub Integration yet.": "您尚未连接到 GitHub 集成。",
  "Back": "返回",
  "Tools": "工具",
  "Developed by": "开发者：",
  "Details": "详情",
  "Author": "作者",
  "Version": "版本",
  "License": "许可证",
  "Source Code": "源代码",
  "Report Issues": "报告问题",
  "Connector URL": "连接器链接",
  "More info": "更多信息",
  "Documentation": "文档",
  "Support": "支持",
  "Disconnect": "取消连接",
  "Tool permissions": "工具权限",
  "Choose when Claude is allowed to use these tools.": "选择 Claude 何时可以使用这些工具。",
  "Interactive tools": "交互式工具",
  "Custom": "自定义",
  "Always allow": "始终允许",
  "Needs approval": "需要批准",
  "Blocked": "阻止",
  "Read-only tools": "只读工具",
  "App-only tools": "仅限应用程序工具",
  "View details": "查看详情",
  "Remove": "移除",
  "However, Claude won’t be able to access new content or perform new tasks.": "但是，Claude 将无法访问新内容或执行新任务。",
  "Copy link": "复制链接",
  "Search your chats...": "搜索对话…",
  "Your chats with Claude": "您与 Claude 的对话",
  "Select": "选择",
};

function isSafeToTranslate(node) {
  if (node.nodeType !== Node.ELEMENT_NODE) return true;

  if (
    node.tagName === 'INPUT' || 
    node.tagName === 'TEXTAREA' || 
    node.isContentEditable
  ) {
    return false;
  }

  if (node.tagName === 'PRE' || node.tagName === 'CODE') {
    return false;
  }

  const className = node.className || "";
  if (typeof className === 'string' && className.includes('prose')) {
    return false;
  }

  return true;
}

const dynamicRules = [
  { regex: /^Good morning,?\s*(.*)$/i, replace: "早上好，$1" },
  { regex: /^Good afternoon,?\s*(.*)$/i, replace: "下午好，$1" },
  { regex: /^Good evening,?\s*(.*)$/i, replace: "晚上好，$1" },
  { regex: /^It's late-night\s*(.*)$/i, replace: "夜深了，$1" },
  { regex: /^Type \/ for (.*)$/i, replace: "输入 / 获取 $1" },
  { regex: /^until\s+(.*)$/i, replace: "额度已用尽，下个可用时间：$1" },
  { 
    regex: /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d+)$/i, 
    replace: function(match, p1, p2) {
      const months = {
        'Jan': '1月', 'Feb': '2月', 'Mar': '3月', 'Apr': '4月', 'May': '5月', 'Jun': '6月',
        'Jul': '7月', 'Aug': '8月', 'Sep': '9月', 'Oct': '10月', 'Nov': '11月', 'Dec': '12月'
      };
      return (months[p1] || p1) + p2 + "日";
    } 
  },
  { regex: /^(.*)\s*\(optional\)$/i, replace: "$1（可选）" },
  { regex: /^#(\d+)\s+popular$/i, replace: "热门榜第 $1 名" },
  { regex: /^Search, access and get insights on your (.*) content$/i, replace: "搜索、访问并获取您的 $1 内容洞察" },
  { regex: /^Manage (.*) and (.*) effortlessly$/i, replace: "轻松管理 $1 和 $2" },
  { regex: /^Connect to (.*) for (.*) and (.*) insights$/i, replace: "连接到 $1 以获取 $2 和 $3 洞察" },
  { regex: /^Search (.*) to power your development$/i, replace: "搜索 $1 以助力您的开发" },
  { regex: /^Remove (.*) ?$/i, replace: "移除 $1" },
  { regex: /^You can still continue previous chats that reference (.*) content.$/i, replace: "您仍然可以继续之前提及 $1 内容的聊天记录。" },
];

function translateNode(node) {
  if (node.parentElement && node.parentElement.tagName === 'KBD') return;

  if (node.nodeType === Node.ELEMENT_NODE) {
    const attrsToCheck = ['placeholder', 'data-placeholder', 'aria-label'];
    attrsToCheck.forEach(attr => {
      if (node.hasAttribute(attr)) {
        const attrText = node.getAttribute(attr).trim();
        if (uiDictionary[attrText]) node.setAttribute(attr, uiDictionary[attrText]);
      }
    });
  }

  if (node.nodeType === Node.TEXT_NODE) {
    const text = node.nodeValue.trim();
    if (!text) return;
    if (text === "New") {
      if (node.parentElement && node.parentElement.closest('[role="menuitemradio"]')) {
        node.nodeValue = node.nodeValue.replace(text, "最新");
        return;
      }
      if (node.parentElement && node.parentElement.classList.contains('text-brand-100')) {
        node.nodeValue = node.nodeValue.replace(text, "新");
        return;
      }
    }

    if (uiDictionary[text]) {
      node.nodeValue = node.nodeValue.replace(text, uiDictionary[text]);
      return;
    }

    for (let rule of dynamicRules) {
      if (rule.regex.test(text)) {
        node.nodeValue = node.nodeValue.replace(text, text.replace(rule.regex, rule.replace));
        break; 
      }
    }
  }
}

function walkDOM(node) {
  translateNode(node);

  if (node.nodeType === Node.ELEMENT_NODE && !isSafeToTranslate(node)) {
    return;
  }

  let child = node.firstChild;
  while (child) {
    walkDOM(child);
    child = child.nextSibling;
  }
}
console.log("[Claude汉化插件] 已启动");

walkDOM(document.body);

const observer = new MutationObserver((mutations) => {
  mutations.forEach((mutation) => {
    if (mutation.addedNodes.length > 0) {
      mutation.addedNodes.forEach((node) => {
        walkDOM(node);
      });
    }
  });
});

observer.observe(document.body, {
  childList: true,
  subtree: true
});
